const fs = require('fs');
const path = require('path');

// Scan images/talks/ folder and generate talks-data.js
const talksDir = path.join(__dirname, 'talks');

if (!fs.existsSync(talksDir)) {
  console.error('Error: images/talks/ directory not found!');
  console.log('Create it with: mkdir -p images/talks');
  process.exit(1);
}

const talks = [];
const folders = fs.readdirSync(talksDir).filter(f => {
  return fs.statSync(path.join(talksDir, f)).isDirectory();
});

folders.forEach(folder => {
  const folderPath = path.join(talksDir, folder);
  const files = fs.readdirSync(folderPath).filter(f => {
    return /\.(jpg|jpeg|png|gif|webp)$/i.test(f);
  });

  // Find thumbnail
  const thumb = files.find(f => /^thumb\.(jpg|jpeg|png|gif|webp)$/i.test(f));

  // Get other images for gallery
  // const galleryImages = files.filter(f => !/^thumb\./i.test(f));
  const galleryImages = files.filter(f => !/^thumb\./i.test(f)).map(f => encodeURIComponent(f))

  if (thumb && galleryImages.length > 0) {
    talks.push({
      folder: folder,
      thumb: thumb,
      images: galleryImages
    });
  }
});

// Generate JavaScript file
const output = `// Auto-generated by scan-images.js
// Run: node scan-images.js to update

const TALKS_DATA = ${JSON.stringify(talks, null, 2)};
`;

fs.writeFileSync('talks-data.js', output);

console.log('✅ Generated talks-data.js');
console.log(`📁 Found ${talks.length} talk folders`);
talks.forEach(talk => {
  console.log(`   ${talk.folder}: ${talk.images.length} images`);
});
console.log('\n💡 Now edit talks.html and add your talk details!');
