// Auto-generated by scan-images.js
// Run: node scan-images.js to update

const TALKS_DATA = [
  {
    "folder": "15OCT25",
    "thumb": "thumb.jpeg",
    "images": [
      "WhatsApp Image 2025-10-10 at 15.05.29.jpeg"
    ]
  },
  {
    "folder": "25OCT25",
    "thumb": "thumb.jpeg",
    "images": [
      "WhatsApp Image 2025-10-22 at 10.27.40.jpeg",
      "WhatsApp Image 2025-10-25 at 14.50.39 (1).jpeg",
      "WhatsApp Image 2025-10-25 at 14.50.39.jpeg",
      "WhatsApp Image 2025-10-25 at 19.44.10.jpeg"
    ]
  }
];
