// Auto-generated by scan-images.js
// Run: node scan-images.js to update

const TALKS_DATA = [
  {
    "folder": "08AUG17",
    "thumb": "thumb.jpg",
    "images": [
      "gist1.jpg",
      "gist2.jpg",
      "gist3.jpg"
    ]
  },
  {
    "folder": "13DEC19",
    "thumb": "thumb.jpg",
    "images": [
      "thumb%20copy.jpg",
      "vit1.jpeg"
    ]
  },
  {
    "folder": "15OCT25",
    "thumb": "thumb.jpeg",
    "images": [
      "WhatsApp%20Image%202025-10-10%20at%2015.05.29.jpeg",
      "thumb%20copy.jpeg"
    ]
  },
  {
    "folder": "25OCT25",
    "thumb": "thumb.jpeg",
    "images": [
      "WhatsApp%20Image%202025-10-22%20at%2010.27.40.jpeg",
      "WhatsApp%20Image%202025-10-25%20at%2014.50.39%20(1).jpeg",
      "WhatsApp%20Image%202025-10-25%20at%2014.50.39.jpeg",
      "WhatsApp%20Image%202025-10-25%20at%2019.44.10.jpeg",
      "copyofthumb.jpeg"
    ]
  }
];
